services:
  ui:
    environment:
      - PORT=${FRONTEND_UI_PORT}
    build:
      dockerfile: ./frontend/Dockerfile
  fastify:
    environment:
      - PORT=${BACKEND_FASTIFY_PORT}
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - ${BACKEND_FASTIFY_PORT}:${BACKEND_FASTIFY_PORT}
  reverse-proxy:
    environment:
      - BACKEND_FASTIFY_PORT=${BACKEND_FASTIFY_PORT}
      - FRONTEND_UI_PORT=${FRONTEND_UI_PORT}
      - PORT=${REVERSE_PROXY_PORT}
    build:
      dockerfile: ./reverse-proxy/Dockerfile
    ports:
      - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}
