services:
  ui:
    env_file: .env
    build:
      dockerfile: ./frontend/Dockerfile
  fastify:
    env_file: .env
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - ${BACKEND_FASTIFY_PORT}:${BACKEND_FASTIFY_PORT}
  reverse-proxy:
    build:
      dockerfile: ./reverse-proxy/Dockerfile
    ports:
      - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}
    env_file: .env