services:
  backend:
    container_name: fastify
    networks:
      - app-network
    build:
      dockerfile_inline: |
        FROM node:20-bullseye
        COPY . .
        RUN apt-get -y update
        RUN apt-get install -y wget
        RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        RUN apt-get install -y ./google-chrome-stable_current_amd64.deb
        RUN corepack enable
        RUN pnpm i
        RUN pnpm build
        EXPOSE 3000
        CMD pnpm start
    ports:
      - ${PORT}:3000
networks:
    app-network:
        driver: bridge