services:
  backend:
    container_name: fastify
    network_mode: "host"
    build:
      dockerfile_inline: |
        FROM node:20-bullseye
        WORKDIR /src
        EXPOSE ${BACKEND_FASTIFY_PORT}
        COPY . .
        RUN apt-get -y update
        RUN curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        RUN apt-get install -y ./google-chrome-stable_current_amd64.deb
        RUN rm google-chrome-stable_current_amd64.deb
        RUN corepack enable
        RUN ls -al .
        RUN pnpm i
        RUN pnpm -F backend build
        CMD pnpm -F backend serve
    ports:
      - ${BACKEND_FASTIFY_PORT}:${BACKEND_FASTIFY_PORT}